require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LieusController do

  def mock_lieu(stubs={})
    @mock_lieu ||= mock_model(Lieu, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lieus as @lieus" do
      Lieu.stub(:all) { [mock_lieu] }
      get :index
      assigns(:lieus).should eq([mock_lieu])
    end
  end

  describe "GET show" do
    it "assigns the requested lieu as @lieu" do
      Lieu.stub(:find).with("37") { mock_lieu }
      get :show, :id => "37"
      assigns(:lieu).should be(mock_lieu)
    end
  end

  describe "GET new" do
    it "assigns a new lieu as @lieu" do
      Lieu.stub(:new) { mock_lieu }
      get :new
      assigns(:lieu).should be(mock_lieu)
    end
  end

  describe "GET edit" do
    it "assigns the requested lieu as @lieu" do
      Lieu.stub(:find).with("37") { mock_lieu }
      get :edit, :id => "37"
      assigns(:lieu).should be(mock_lieu)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lieu as @lieu" do
        Lieu.stub(:new).with({'these' => 'params'}) { mock_lieu(:save => true) }
        post :create, :lieu => {'these' => 'params'}
        assigns(:lieu).should be(mock_lieu)
      end

      it "redirects to the created lieu" do
        Lieu.stub(:new) { mock_lieu(:save => true) }
        post :create, :lieu => {}
        response.should redirect_to(lieu_url(mock_lieu))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lieu as @lieu" do
        Lieu.stub(:new).with({'these' => 'params'}) { mock_lieu(:save => false) }
        post :create, :lieu => {'these' => 'params'}
        assigns(:lieu).should be(mock_lieu)
      end

      it "re-renders the 'new' template" do
        Lieu.stub(:new) { mock_lieu(:save => false) }
        post :create, :lieu => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lieu" do
        Lieu.stub(:find).with("37") { mock_lieu }
        mock_lieu.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lieu => {'these' => 'params'}
      end

      it "assigns the requested lieu as @lieu" do
        Lieu.stub(:find) { mock_lieu(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lieu).should be(mock_lieu)
      end

      it "redirects to the lieu" do
        Lieu.stub(:find) { mock_lieu(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lieu_url(mock_lieu))
      end
    end

    describe "with invalid params" do
      it "assigns the lieu as @lieu" do
        Lieu.stub(:find) { mock_lieu(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lieu).should be(mock_lieu)
      end

      it "re-renders the 'edit' template" do
        Lieu.stub(:find) { mock_lieu(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lieu" do
      Lieu.stub(:find).with("37") { mock_lieu }
      mock_lieu.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lieus list" do
      Lieu.stub(:find) { mock_lieu }
      delete :destroy, :id => "1"
      response.should redirect_to(lieus_url)
    end
  end

end
